### ISSUE TITLE
Struct wrappers with un-inited interfaces panic on String()

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#29]
ie. https://play.golang.org/p/8PPu0PBr-x

or 

```
package main

import (
	"fmt"
)

type Wrapper1 struct {
	Interface1
}

type Interface1 interface {
}

type Wrapper2 struct {
	Interface2
}


type Interface2 interface {
	String() string
}

func main() {
	var good Wrapper1
	var bad Wrapper2
	fmt.Println(good)
	fmt.Println(bad)
}

```

In the context of this library, the following prints a panic. 

```
var sig Signature
fmt.Println(sig)
```

Is there a way to solve this without making a default Nil implementation of the interface for everything that has a `String()` ? Ie. `SignatureNil`.

**Comment by odeke-em** [comment]
@ebuchman sorry if this is a dumb question, but would you mind pointing to actual source code that uses this? IMHO that code's structure, composing an interface into a struct looks iffy and maybe we could take a look at redesigning that if possible, because so far I don't think there is any way we can get around it without implementing a .String() method.

From an eyeballing, was perhaps the intention of composing that interface into the struct so that the struct could satisfy the interface sneakishly, without us having to write the code for it? If so, I'd advise that we rip the composition out and instead do a compile time type assertion, and then write the actual method to avoid such runtime panics.

**Comment by ethanfrey** [comment]
The purpose was to add methods to anything that satisfies the interface. And you can add methods directly to an interface..... 

Namely, we use it to override json marshaling and a few other things. 

The struct could also implement a String dispatcher or anything else we need to work on empty structs. 

However, any code calling string on a nil interface would panic anyway, a caller should ensure non nil. For these structs, check Empty() returns false

Do we want to have the struct save people from no checking for nil? Or fix the callers?

**Comment by ethanfrey** [comment]
If it is only for debugging statements, I can get behind making this safer

**Comment by ethanfrey** [comment]
Actually I think the solution is to remove the String method from the signature interface. Fmt. Println will find it if implemented using reflection, no need to declare. 

Also the assert signature method is redundant now that we have wrap

**Comment by ebuchman** [comment]
Yes maybe we just remove the `String()` ! I'll take a look at that
